clone_depth: 1

install:
    - git submodule update --init
    - cd c:\
    - choco install -y wget
    - mkdir C:\deps

    - wget https://anaconda.org/conda-forge/log4cpp/1.1.3/download/win-64/log4cpp-1.1.3-h6538335_1001.tar.bz2 -O "log4cpp.tar.bz2"
    - mkdir C:\deps\log4cpp
    - tar -C C:\deps\log4cpp -xf log4cpp.tar.bz2
    - rm log4cpp.tar.bz2
        
    - wget https://anaconda.org/anaconda/mpir/3.0.0/download/win-64/mpir-3.0.0-hec2e145_1.tar.bz2 -O "mpir.tar.bz2"
    - mkdir C:\deps\mpir
    - tar -C C:\deps\mpir -xf mpir.tar.bz2
    - rm mpir.tar.bz2
        
    - wget https://sourceforge.net/projects/swig/files/swigwin/swigwin-3.0.8/swigwin-3.0.8.zip -O "swig.zip"
    - mkdir C:\deps\swig
    - unzip swig.zip -d C:\deps\swig\
        
    - pip install mako
    - pip install six
        
    - vcpkg install fftw3:x64-windows

build_script:
    - mkdir c:\projects\gnuradio\build
    - cd c:\projects\gnuradio\build
    - cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSWIG_EXECUTABLE:FILEPATH=C:/deps/swig/swigwin-3.0.8/swig.exe -DLOG4CPP_INCLUDE_DIR:PATH=C:/deps/log4cpp/Library/include -DLOG4CPP_LIBRARY:FILEPATH=C:/deps/log4cpp/Library/lib/log4cpp.lib -DMPIR_INCLUDE_DIR:PATH=C:/deps/mpir/Library/include -DMPIR_LIBRARY:FILEPATH=C:/deps/mpir/Library/lib/mpir_static.lib -DMPIRXX_INCLUDE_DIR:PATH=C:/deps/mpir/Library/include -DMPIRXX_LIBRARY:FILEPATH=C:/deps/mpir/Library/lib/mpirxx_static.lib -DENABLE_INTERNAL_VOLK:BOOL=ON -DENABLE_GR_FEC:BOOL=OFF -DENABLE_GR_DIGITAL:BOOL=OFF -DENABLE_GR_DTV:BOOL=OFF -DENABLE_GR_ATSC:BOOL=OFF -DENABLE_GR_AUDIO:BOOL=OFF -DENABLE_GR_CHANNELS:BOOL=OFF -DENABLE_GR_NOAA:BOOL=OFF \ -DENABLE_GR_PAGER:BOOL=OFF -DENABLE_GR_TRELLIS:BOOL=OFF -DENABLE_GR_VOCODER:BOOL=OFF -A x64 ..
    - cmake --build . --config Release --target INSTALL
    # Create an archive
    - cd "c:\Program Files"
    - 7z a "c:\gnuradio-x64.zip" gnuradio
    - appveyor PushArtifact c:\gnuradio-x64.zip
