clone_depth: 1

image:
  - Visual Studio 2017

environment:
    PYTHON: C:\Python37-x64
    QT: C:\Qt\5.13.2\msvc2017_64
    MINGW_VERSION: mingw64
    VS: "Visual Studio 15 Win64"
    ARCH: x86_64
    ARCH_BIT: 64
    matrix:
        - COMPILER: mingw
        - COMPILER: vs

matrix:
    fast_finish: true

cache: c:\tools\vcpkg\installed\

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "SET PATH=%QT%;%PATH%"
    - git submodule update --init
    - cd c:\
    - choco install -y wget
    - choco install -y svn
    - mkdir C:\deps
    - if [[ $COMPILER == 'mingw' ]]; then C:\msys64\usr\bin\bash C:\projects\gnuradio\install_mingw.sh ; fi
    - if [[ $COMPILER == 'vs' ]]; then C:\projects\gnuradio\install_vs.sh ; fi
    - pip install sphinx
    - pip install pyqt5
    - pip install pythonqwt
    - pip install mako
    - pip install six
    - pip install pyyaml
    - pip install click
    - pip install click-plugins
    - pip install numpy

build_script:
    - if [[ $COMPILER == 'mingw' ]]; then cd C:\projects\gnuradio; C:\msys64\usr\bin\bash build_mingw.sh; fi
    - if [[ $COMPILER == 'vs' ]]; then C:\projects\gnuradio\build_vs.bat; fi
